# Generated by Django 5.1.1 on 2024-11-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('description', models.CharField(max_length=1000)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('attacks', models.IntegerField()),
                ('ws', models.IntegerField()),
                ('dmg', models.IntegerField()),
                ('critical_dmg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('description', models.CharField(max_length=1000)),
                ('modifier', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('cost', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('faction', models.CharField(max_length=240)),
                ('ability', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warhammer.ability')),
            ],
        ),
        migrations.CreateModel(
            name='Operative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('movement', models.IntegerField(default=3)),
                ('dash', models.IntegerField()),
                ('apl', models.IntegerField()),
                ('ga', models.IntegerField()),
                ('df', models.IntegerField()),
                ('sv', models.IntegerField()),
                ('w', models.IntegerField()),
                ('base', models.IntegerField()),
                ('gun', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warhammer.gun')),
                ('unique_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warhammer.uniqueaction')),
            ],
        ),
        migrations.CreateModel(
            name='CustomArmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.army')),
                ('operative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.operative')),
            ],
        ),
        migrations.AddField(
            model_name='army',
            name='operatives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warhammer.operative'),
        ),
        migrations.CreateModel(
            name='OperativeGun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.gun')),
                ('operative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.operative')),
            ],
        ),
        migrations.AddField(
            model_name='gun',
            name='special_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warhammer.specialrule'),
        ),
    ]
