# Generated by Django 5.1.1 on 2024-11-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opperative',
            new_name='Operative',
        ),
    ]
