# Generated by Django 5.1.1 on 2024-11-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operative',
            name='gun',
        ),
        migrations.AddField(
            model_name='operative',
            name='gun',
            field=models.ManyToManyField(blank=True, to='warhammer.gun'),
        ),
    ]
