# Generated by Django 5.1.1 on 2024-11-26 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0002_rename_opperative_operative'),
    ]

    operations = [
        migrations.AddField(
            model_name='operative',
            name='gun',
            field=models.ManyToManyField(blank=True, to='warhammer.gun'),
        ),
        migrations.AddField(
            model_name='operativegun',
            name='gun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warhammer.gun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operativegun',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name='army',
            name='operatives',
        ),
        migrations.AlterField(
            model_name='operative',
            name='unique_action',
            field=models.ManyToManyField(blank=True, to='warhammer.uniqueaction'),
        ),
        migrations.AddField(
            model_name='army',
            name='operatives',
            field=models.ManyToManyField(to='warhammer.operative'),
        ),
    ]
