# Generated by Django 5.1.1 on 2024-11-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0003_operative_gun_operativegun_gun_operativegun_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='ability',
        ),
        migrations.AddField(
            model_name='army',
            name='ability',
            field=models.ManyToManyField(blank=True, to='warhammer.ability'),
        ),
    ]
