# Generated by Django 5.1.1 on 2024-11-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0003_operative_gun_operativegun_gun_operativegun_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customarmy',
            name='operative',
        ),
        migrations.AddField(
            model_name='customarmy',
            name='operative',
            field=models.ManyToManyField(to='warhammer.operativegun'),
        ),
    ]
