# Generated by Django 5.1.1 on 2024-11-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0004_remove_customarmy_operative_customarmy_operative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operativegun',
            name='gun',
        ),
        migrations.AddField(
            model_name='operativegun',
            name='gun',
            field=models.ManyToManyField(to='warhammer.gun'),
        ),
    ]
