# Generated by Django 5.1.1 on 2024-11-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0006_alter_operativegun_operative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativegun',
            name='gun',
            field=models.ManyToManyField(blank=True, null=True, to='warhammer.gun'),
        ),
    ]
