# Generated by Django 5.1.1 on 2024-12-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0005_alter_army_ability_alter_army_name'),
        ('warhammer', '0006_alter_customarmy_army_alter_customarmy_operative_and_more'),
    ]

    operations = [
    ]
