# Generated by Django 5.1.1 on 2024-12-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0005_alter_army_ability_alter_army_name'),
        ('warhammer', '0007_alter_operativegun_gun'),
    ]

    operations = [
    ]
