# Generated by Django 5.1.1 on 2024-12-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0007_merge_20241201_0401'),
        ('warhammer', '0008_merge_20241201_0446'),
    ]

    operations = [
    ]
